a161527/cs319-p2t5

app/Http/Controllers/Events.php, app/Http/routes.php
changes have been merged from post revert to testShehryar
=> back to initial testShehryar branch. 

app/Conference.php, app/Exceptions/Handler.php, app/Http/Controllers/ConferenceController.php, tests/ConferenceTest.php
This fixes/tests the conference endpoints with the new database stuff.
=> Update Conference Endpoints

app/Http/Controllers/AuthenticationController.php, app/Http/Controllers/ConferenceController.php, app/Utility/PermissionNames.php, app/Utility/RoleCreate.php, database/seeds/DefaultPermissionsSeeder.php, database/seeds/DefaultRolesSeeder.php, tests/GlobalPermissionTest.php
Adds a full permission list that covers everything we know we'll need.
=> Full permission list

app/Http/Controllers/ConfRegistrationController.php, app/Http/Controllers/ConferenceController.php, app/Http/Kernel.php, app/Http/routes.php, app/UserConference.php, app/Utility/ConferenceRegistrationUtils.php, app/Utility/PermissionNames.php, tests/ConferenceTest.php
A GET to /api/conferences/{confId}/permissions will get a list of conference permissions for the current user.
(With conference ID stripped from the end)
=> Conference Permission endpoint, along with tests.

app/Utility/ConferenceRegistrationUtils.php
=> Fix registration info grab if no user is logged in

app/Http/Controllers/Conference/MainController.php, app/Utility/PermissionNames.php, app/Utility/RoleCreate.php, database/seeds/ConferenceTableSeeder.php, tests/ConferenceTest.php
This also fixes a few tests, so going to merge this first part in.
=> Change to single method to create all conference permissions

app/Http/Controllers/RegistrationController.php
Added a bunch of missing stuff I thought I had (might've gotten lost from before? I honestly have no idea)
=> Fixes for account registration

public/index.html, public/js/app/app.config.js, public/js/conferenceRegistrationDetails/conferenceRegistrationDetails.view.html, public/js/rooms/rooms.controller.allocate.js, public/js/rooms/rooms.service.getRoomUsers.js, public/js/rooms/rooms.view.roomList.html
Note: dependents list in assign rooms now only shows users approved for the conference.
=> Assign rooms reworked

public/js/app/app.config.js, public/js/conferenceView/conferenceView.service.conferenceList.js, public/js/conferenceWidget/conferenceWidget.controller.js, public/js/conferenceWidget/conferenceWidget.view.html, public/js/rooms/rooms.controller.allocate.js, public/js/rooms/rooms.service.getRoomUsers.js, public/js/rooms/rooms.view.html
Please check that everything still works. We only really need to worry about the things within the dashboard. I have tested most of it already and it should be OK, but I could be missing somethings.
=> Changed urls and state names

app/Http/Controllers/Conference/RoomSetupController.php
=> Make residence/roomset creation endpoints take lists

app/Http/Controllers/TransportationController.php, app/Http/routes.php, app/Transportation.php, app/UserConference.php, app/UserTransportation.php, database/migrations/2016_02_20_020916_create_table_transportation.php, database/migrations/2016_02_20_020917_create_table_user_transportation.php, database/migrations/2016_03_27_084914_add_info_columns_to_transportation_table.php, vendor/composer/autoload_classmap.php
…ceID, a flightID, both or neither (lists all)), add, delete, edit, assignFlight
=> Transportation management (add, delete, etc.)

app/Http/Controllers/Events.php
=> Add `includePermissions` parameter for events

app/Http/Controllers/Conference/RoomSetupController.php, app/Http/Controllers/InventoryController.php, app/Http/routes.php
=> Individual item endpoints

app/Http/Controllers/AuthenticationController.php, app/Http/Controllers/Conference/MainController.php, app/Http/Controllers/Conference/RegistrationController.php, app/Http/Controllers/Conference/RoomAssignmentController.php, app/Http/Controllers/Conference/RoomSetupController.php, app/Http/Controllers/Events.php, app/Http/Controllers/InventoryController.php, app/Http/Controllers/PermissionsController.php, app/Http/Controllers/RegistrationController.php, app/Http/Controllers/UserController.php, app/Http/Kernel.php, app/Http/Middleware/JWTAuthWithRejection.php, app/Http/routes.php, app/Utility/PermissionNames.php, database/seeds/DefaultPermissionsSeeder.php
Implements some of the stuff from #89
=> Deletion endpoints

app/Http/Controllers/InventoryController.php, app/Http/routes.php
Fixes #116 
Does change the endpoint slightly - it's now `/api/conferences/{cid}/userinventory/{reqId}/approve`
=> Fix inventory approval endpoint

app/Http/Controllers/TransportationController.php
Depends on #102 so need to get that in first
=> Check at least a bit of permission stuff for transport

public/js/createInventory/createInventory.controller.js
pass in conf id as int and fix field name for totalQuantity
=> fix for #125

public/js/createEvent/createEvent.controller.js
fixing mismatched variable names
=> fix for #121

app/Http/routes.php, public/css/custom.css, public/index.html, public/js/app/app.run.js, public/js/conferenceView/conferenceView.controller.conferenceList.js, public/js/conferenceView/conferenceView.view.conferenceList.html, public/js/conferenceWidget/conferenceWidget.view.html, public/js/dashboard/dashboard.view.html, public/js/eventView/eventView.controller.eventList.js, public/js/eventView/eventView.view.eventList.html, public/js/forms/forms.service.confirmDeleteModal.js, public/js/forms/forms.view.confirmDelete.html, public/js/inventoryView/inventoryView.controller.js, public/js/inventoryView/inventoryView.view.html, public/js/residenceView/residenceView.controller.js, public/js/residenceView/residenceView.view.html, public/js/roomSetView/roomSetView.controller.js, public/js/roomSetView/roomSetView.view.html, public/js/transportationView/transportationView.controller.js, public/js/transportationView/transportationView.view.html
Deletion for the following objects:
- conference
- event
- inventory
- residence
- room set
- transportation
buttons are available on list view pages
=> object deletion

public/js/conferenceView/conferenceView.view.conferenceList.html, public/js/eventView/eventView.view.eventList.html, public/js/inventoryView/inventoryView.view.html, public/js/residenceView/residenceView.view.html, public/js/roomSetView/roomSetView.view.html, public/js/transportationView/transportationView.view.html
added filter for following list views:
- conference
- event
- inventory
- residence
- room set
- transportation
=> filter for list views

public/js/app/app.run.js, public/js/auditAccts/auditAccts.view.assign.html, public/js/login/login.service.loginStorage.js
- fixing event edit access permissions
- submit email to assign permissions on enter
=> bug fixes and ui improvements

public/js/createConference/createConference.view.html, public/js/createEvent/createEvent.view.html
input only accepts alphanumeric characters and white space
=> prevent special characters in event and conference names
